/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.ncirl.softeng.security;

import javax.swing.JOptionPane;

/**
 *
 * @author x12317886 Fiachra Devitt
 */
public class BankSecGUI extends javax.swing.JFrame {

    private Clients cs;
    private long cardNum;
    private int pinNum;

    /**
     * Creates new form BankSecGUI
     */
    public BankSecGUI(Clients cs) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JBank Inc.");
        this.cs = cs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        backBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        PinNumLbl = new javax.swing.JLabel();
        clientIdLbl = new javax.swing.JLabel();
        clientIdTf = new javax.swing.JTextField();
        InfoLbL = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        pinNumPf = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(0, 470, 370, 33);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        confirmBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });
        confirmBtn.setBounds(0, 300, 370, 33);
        jLayeredPane1.add(confirmBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PinNumLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PinNumLbl.setText("Pin Number:");
        PinNumLbl.setBounds(10, 200, 110, 14);
        jLayeredPane1.add(PinNumLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        clientIdLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clientIdLbl.setText("Client ID:");
        clientIdLbl.setBounds(10, 130, 130, 14);
        jLayeredPane1.add(clientIdLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        clientIdTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIdTfActionPerformed(evt);
            }
        });
        clientIdTf.setBounds(10, 150, 350, 33);
        jLayeredPane1.add(clientIdTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        InfoLbL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        InfoLbL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoLbL.setText("<html> Please enter and confirm the number and pin<br /> of your lost/stolen credit card below. </html>");
        InfoLbL.setBounds(0, 60, 370, 30);
        jLayeredPane1.add(InfoLbL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbl.setText("Credit Card Recovery");
        TitleLbl.setBounds(0, 10, 370, 29);
        jLayeredPane1.add(TitleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pinNumPf.setBounds(10, 220, 350, 30);
        jLayeredPane1.add(pinNumPf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LoginGUI myLogin = new LoginGUI();
        myLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void clientIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIdTfActionPerformed
    }//GEN-LAST:event_clientIdTfActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        checkClient();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void checkClient() {
        Admin a = new Admin();
        String clientId = clientIdTf.getText();
        char[] digitPass = pinNumPf.getPassword();

        
        if (a.validateAdmin(clientId, digitPass)) {
            a.setCardBlocked(true);
            if (a.isCardBlocked()) {
                JOptionPane.showMessageDialog(rootPane, "Card blocked.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error.");
            }
        } else {
            cs.setFetchedClientId(clientId);
            cs.setFetchedDigitPass(digitPass);

            if (cs.compareDetails()) {
                JOptionPane.showMessageDialog(rootPane, "Login successfull as " + cs.getName(clientId));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Login Failed");
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InfoLbL;
    private javax.swing.JLabel PinNumLbl;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel clientIdLbl;
    private javax.swing.JTextField clientIdTf;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField pinNumPf;
    // End of variables declaration//GEN-END:variables
}
