/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.ncirl.softeng.security;

import ie.ncirl.softeng.clients.Client;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author x12317886 Fiachra Devitt
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    private String clientId;
    private char[] textPass, digitPass;
    private Admin a = new Admin();
    Clients cs = new Clients();
    static Client c;

    public LoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JBank Inc.");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl = new javax.swing.JLabel();
        infoLbl = new javax.swing.JLabel();
        clientIdLbl = new javax.swing.JLabel();
        textPassLbl = new javax.swing.JLabel();
        digitPassLbl = new javax.swing.JLabel();
        clientIdTf = new javax.swing.JTextField();
        textPassPf = new javax.swing.JPasswordField();
        digitPassPf = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        cardStolenBtn = new javax.swing.JButton();
        forgottenPassLbl = new javax.swing.JLabel();
        adminBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Bank App");
        titleLbl.setBounds(0, 30, 370, 40);
        jLayeredPane1.add(titleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        infoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLbl.setText("<html>\nPlease fill in the details below to access your account.<br /> You should have recieved them by post from your branch.\n</html>");
        infoLbl.setBounds(0, 90, 370, 70);
        jLayeredPane1.add(infoLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        clientIdLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clientIdLbl.setText("ClientID:");
        clientIdLbl.setBounds(10, 150, 60, 30);
        jLayeredPane1.add(clientIdLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textPassLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textPassLbl.setText("Text Password:");
        textPassLbl.setBounds(10, 210, 100, 30);
        jLayeredPane1.add(textPassLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        digitPassLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        digitPassLbl.setText("6-Digit Password:");
        digitPassLbl.setBounds(10, 270, 110, 30);
        jLayeredPane1.add(digitPassLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        clientIdTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientIdTfActionPerformed(evt);
            }
        });
        clientIdTf.setBounds(10, 180, 350, 30);
        jLayeredPane1.add(clientIdTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textPassPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPassPfActionPerformed(evt);
            }
        });
        textPassPf.setBounds(10, 240, 350, 30);
        jLayeredPane1.add(textPassPf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        digitPassPf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitPassPfActionPerformed(evt);
            }
        });
        digitPassPf.setBounds(10, 300, 350, 30);
        jLayeredPane1.add(digitPassPf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtn.setBounds(0, 350, 370, 30);
        jLayeredPane1.add(loginBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cardStolenBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cardStolenBtn.setText("Card Stolen");
        cardStolenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardStolenBtnActionPerformed(evt);
            }
        });
        cardStolenBtn.setBounds(0, 470, 370, 30);
        jLayeredPane1.add(cardStolenBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        forgottenPassLbl.setForeground(new java.awt.Color(0, 102, 255));
        forgottenPassLbl.setText("<html><u style=\"color: blue;\">Forgotten Password</u></html>");
        forgottenPassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgottenPassLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgottenPassLblMouseEntered(evt);
            }
        });
        forgottenPassLbl.setBounds(140, 390, 120, 40);
        jLayeredPane1.add(forgottenPassLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        adminBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminBtn.setText("Admin Terminal");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        adminBtn.setBounds(0, 430, 370, 30);
        jLayeredPane1.add(adminBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientIdTfActionPerformed
        login();
    }//GEN-LAST:event_clientIdTfActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        login();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgottenPassLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgottenPassLblMouseEntered
        forgottenPassLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_forgottenPassLblMouseEntered

    private void digitPassPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitPassPfActionPerformed
        login();
    }//GEN-LAST:event_digitPassPfActionPerformed

    private void textPassPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPassPfActionPerformed
        login();
    }//GEN-LAST:event_textPassPfActionPerformed

    private void forgottenPassLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgottenPassLblMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Redirection will be soon made to the password recovery page");
    }//GEN-LAST:event_forgottenPassLblMouseClicked

    private void cardStolenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardStolenBtnActionPerformed
        BankSecGUI myBankSec = new BankSecGUI(cs);
        myBankSec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cardStolenBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        AdminTerminalGui admin = new AdminTerminalGui(cs);
        admin.setVisible(true);
    }//GEN-LAST:event_adminBtnActionPerformed

    private void login() {
        clientId = clientIdTf.getText();
        textPass = textPassPf.getPassword();
        digitPass = digitPassPf.getPassword();

        if (a.validateAdmin(clientId, textPass, digitPass)) {
            SubsystemsGui sg = new SubsystemsGui(c);
            this.dispose();
            sg.setVisible(true);
        } else {
            cs.setFetchedClientId(clientId);
            cs.setFetchedTextPass(textPass);
            cs.setFetchedDigitPass(digitPass);
            //System.out.println(clientId +":" + textPass + ":" + digitPass);

            if (cs.compareDetails()) {
                SubsystemsGui sg = new SubsystemsGui(c);
                this.dispose();
                sg.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Login Failed");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton cardStolenBtn;
    private javax.swing.JLabel clientIdLbl;
    private javax.swing.JTextField clientIdTf;
    private javax.swing.JLabel digitPassLbl;
    private javax.swing.JPasswordField digitPassPf;
    private javax.swing.JLabel forgottenPassLbl;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel textPassLbl;
    private javax.swing.JPasswordField textPassPf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
