/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.ncirl.softeng.security;

import ie.ncirl.softeng.clients.Client;
import ie.ncirl.softeng.loans.LoanSysGui;
import ie.ncirl.softeng.accounts.AccountsMenu;
import ie.ncirl.softeng.investments.InvestmentGui;

/**
 *
 * @author x12560723
 */
public class SubsystemsGui extends javax.swing.JFrame {

    /**
     * Creates new form SubsystemsGui
     */
    
    Client c;
    
    public SubsystemsGui(Client c) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JBank Inc.");
        this.c = c;
        //System.out.println(this.c.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        container = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        loansBtn = new javax.swing.JButton();
        accMgmtBtn = new javax.swing.JButton();
        investBtn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        container.add(jLabel2);
        jLabel2.setBounds(0, 30, 370, 40);

        logOutBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });
        container.add(logOutBtn);
        logOutBtn.setBounds(0, 470, 370, 30);

        loansBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loansBtn.setText("Your Loans");
        loansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loansBtnActionPerformed(evt);
            }
        });
        container.add(loansBtn);
        loansBtn.setBounds(0, 160, 370, 30);

        accMgmtBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        accMgmtBtn.setText("Account Management");
        accMgmtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accMgmtBtnActionPerformed(evt);
            }
        });
        container.add(accMgmtBtn);
        accMgmtBtn.setBounds(0, 200, 370, 30);

        investBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        investBtn.setText("Investment Banking");
        investBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investBtnActionPerformed(evt);
            }
        });
        container.add(investBtn);
        investBtn.setBounds(0, 240, 370, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void loansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loansBtnActionPerformed
        LoanSysGui lsg = new LoanSysGui(c);
        lsg.setVisible(true);
    }//GEN-LAST:event_loansBtnActionPerformed

    private void accMgmtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accMgmtBtnActionPerformed
        AccountsMenu am = new AccountsMenu(c);
        am.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accMgmtBtnActionPerformed

    private void investBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investBtnActionPerformed
        InvestmentGui ig = new InvestmentGui(c);
        ig.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_investBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accMgmtBtn;
    private javax.swing.JLayeredPane container;
    private javax.swing.JButton investBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loansBtn;
    private javax.swing.JButton logOutBtn;
    // End of variables declaration//GEN-END:variables
}
