/*
 * File Name:
 * Author: Dylan Walker
 * Date:
 */
package ie.ncirl.softeng.accounts;

import ie.ncirl.softeng.clients.Client;
import ie.ncirl.softeng.security.SubsystemsGui;

/**
 *
 * @author dylan3sixty5
 */
public class AccountsMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    Client c;
    
    public AccountsMenu(Client c) {
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
        double currBalance;
        try {
            currBalance = Double.parseDouble(c.getCurrentBalance());
        } catch (NumberFormatException nfe){
            currBalance = 0;
        }
        balanceLbl.setText("Your current balance: " + currBalance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl = new javax.swing.JLabel();
        balanceLbl = new javax.swing.JLabel();
        transferBtn = new javax.swing.JButton();
        statementsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Acounts Management");
        jLayeredPane1.add(titleLbl);
        titleLbl.setBounds(0, 20, 370, 40);

        balanceLbl.setText("Your current balance: ");
        jLayeredPane1.add(balanceLbl);
        balanceLbl.setBounds(15, 110, 350, 20);

        transferBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transferBtn.setText("Transfer money");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(transferBtn);
        transferBtn.setBounds(0, 150, 370, 30);

        statementsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        statementsBtn.setText("Display statement");
        statementsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statementsBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(statementsBtn);
        statementsBtn.setBounds(0, 190, 370, 30);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(0, 459, 370, 30);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(386, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
        TransferMoney tm = new TransferMoney(c);
        tm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transferBtnActionPerformed

    private void statementsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statementsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statementsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        SubsystemsGui sg = new SubsystemsGui(c);
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel balanceLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton statementsBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton transferBtn;
    // End of variables declaration//GEN-END:variables
}
