/*
 * File Name:
 * Author: Dylan Walker
 * Date:
 */
package ie.ncirl.softeng.accounts;

import ie.ncirl.softeng.clients.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author dylan3sixty5
 */
public class TransferMoney extends javax.swing.JFrame {

    /**
     * Creates new form TransferMoney
     */
    Client c;

    public TransferMoney(Client c) {
        initComponents();
        setLocationRelativeTo(null);
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl = new javax.swing.JLabel();
        targetLbl = new javax.swing.JLabel();
        amountTf = new javax.swing.JTextField();
        amountLbl = new javax.swing.JLabel();
        targetTf = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("MoneyTransfer");
        jLayeredPane1.add(titleLbl);
        titleLbl.setBounds(0, 50, 370, 30);

        targetLbl.setText("Target account number:");
        jLayeredPane1.add(targetLbl);
        targetLbl.setBounds(10, 120, 350, 14);

        amountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTfActionPerformed(evt);
            }
        });
        jLayeredPane1.add(amountTf);
        amountTf.setBounds(0, 220, 370, 40);

        amountLbl.setText("Amount:");
        jLayeredPane1.add(amountLbl);
        amountLbl.setBounds(10, 200, 360, 14);

        targetTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetTfActionPerformed(evt);
            }
        });
        jLayeredPane1.add(targetTf);
        targetTf.setBounds(0, 140, 370, 40);

        sendBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendBtn.setText("Send Money");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(sendBtn);
        sendBtn.setBounds(0, 280, 370, 30);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(backBtn);
        backBtn.setBounds(0, 469, 370, 30);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTfActionPerformed

    private void targetTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetTfActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        double amount = 0;
        double balance = 0;
        try {
            balance = Double.parseDouble(c.getCurrentBalance());
        } catch (NumberFormatException nfe) {
            balance = 0;
        }
        String target = targetTf.getText();
        boolean nfException = false;

        try {
            amount = Double.parseDouble(amountTf.getText());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Please check your amount.");
            nfException = true;
        }

        //first statement checks to make sure string is not empty 
        //second makes sure the varible isn't empty 
        System.out.println("'" + target + "'");
        if (target.isEmpty() || target == null) {
            JOptionPane.showMessageDialog(rootPane, "Please check your target account.");
        } else {
            if ((amount <= 3000) && (amount != 0.0) && ((balance - amount) > 0)) {
                JOptionPane.showMessageDialog(rootPane, "Your money has been successfully transfered");
            } else {
                if (nfException == false) {
                    JOptionPane.showMessageDialog(rootPane, "Amount cannot exceed €3000 and has to be greater than €0.\nPlease check your details and try again");
                }
            }
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        AccountsMenu m = new AccountsMenu(c);
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTf;
    private javax.swing.JButton backBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton sendBtn;
    private javax.swing.JLabel targetLbl;
    private javax.swing.JTextField targetTf;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
