/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.ncirl.softeng.loans;

import ie.ncirl.softeng.clients.Client;
import javax.swing.JOptionPane;

/**
 *
 * @author x12560723
 */
public class LoanRequestGui extends javax.swing.JFrame {

    /**
     * Creates new form LoanRequestGui
     */
    Client c;

    public LoanRequestGui(Client c) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JBank Inc.");
        this.c = c;
        calcBtn.setText("Interest: --%");
        //System.out.println(this.c.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl = new javax.swing.JLabel();
        amountLbl = new javax.swing.JLabel();
        periodTf = new javax.swing.JTextField();
        periodLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        calcBtn = new javax.swing.JButton();
        amountTf = new javax.swing.JTextField();
        requestBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Loan Request");
        titleLbl.setBounds(0, 30, 370, 40);
        jLayeredPane1.add(titleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        amountLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountLbl.setText("Amount:");
        amountLbl.setBounds(10, 150, 60, 30);
        jLayeredPane1.add(amountLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        periodTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodTfActionPerformed(evt);
            }
        });
        periodTf.setBounds(10, 240, 350, 30);
        jLayeredPane1.add(periodTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        periodLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        periodLbl.setText("Time span (in months, no more than 72):");
        periodLbl.setBounds(10, 210, 350, 30);
        jLayeredPane1.add(periodLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(0, 460, 370, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        calcBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcBtn.setText("Interest: --%");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });
        calcBtn.setBounds(0, 320, 370, 40);
        jLayeredPane1.add(calcBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        amountTf.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                amountTfCaretUpdate(evt);
            }
        });
        amountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTfActionPerformed(evt);
            }
        });
        amountTf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountTfKeyTyped(evt);
            }
        });
        amountTf.setBounds(10, 180, 350, 30);
        jLayeredPane1.add(amountTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        requestBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestBtn.setText("Request");
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });
        requestBtn.setBounds(0, 370, 370, 40);
        jLayeredPane1.add(requestBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void periodTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodTfActionPerformed
        // NOT USED
    }//GEN-LAST:event_periodTfActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LoanSysGui lsg = new LoanSysGui(c);
        lsg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        int amount = 0;
        int period = 0;
        int interest = -1;
        try {
            amount = Integer.parseInt(amountTf.getText());
            period = Integer.parseInt(periodTf.getText());
            interest = calculateCommision(amount, period);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Please make sure you input both values correctly");
        }
        if (interest == -1) {
            calcBtn.setText("Interest: --%");
        } else {
            calcBtn.setText("Interest: " + interest + "%");
        }
    }//GEN-LAST:event_calcBtnActionPerformed

    private void amountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTfActionPerformed
        // NOT USED
    }//GEN-LAST:event_amountTfActionPerformed

    private void amountTfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountTfKeyTyped
        // NOT USED
    }//GEN-LAST:event_amountTfKeyTyped

    private void amountTfCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_amountTfCaretUpdate
        // NOT USED
    }//GEN-LAST:event_amountTfCaretUpdate

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        long amount = Long.parseLong(amountTf.getText());
        String status = "Reviewed";
        c.loans.add(new Loan(amount, status));
        JOptionPane.showMessageDialog(rootPane, "Loan send for review.");
    }//GEN-LAST:event_requestBtnActionPerformed

    public int calculateCommision(int amount, int period) {

        int interest;
        interest = -1;
        if (period > 0 && period <= 12) {
            if (amount > 0 && amount <= 500) {
                interest = 15;
            } else if (amount > 500 && amount <= 1000) {
                interest = 13;
            } else if (amount > 1000 && amount <= 5000) {
                interest = 10;
            } else if (amount > 5000) {
                interest = -1;
            } else {
                interest = -1;
            }
        } else if (period > 12 && period <= 24) {
            if (amount > 0 && amount <= 500) {
                interest = 17;
            } else if (amount > 500 && amount <= 1000) {
                interest = 15;
            } else if (amount > 1000 && amount <= 5000) {
                interest = 15;
            } else if (amount > 5000 && amount <= 20000) {
                interest = 20;
            } else if (amount > 20000) {
                interest = -1;
            } else {
                interest = -1;
            }
        } else if (period > 24 && period <= 72) {
            if (amount > 1000 && amount <= 5000) {
                interest = 13;
            } else if (amount > 5000 && amount <= 20000) {
                interest = 15;
            } else if (amount > 20000) {
                interest = -1;
            } else {
                interest = -1;
            }
        } else if (period > 72) {
            if (amount > 5000 && amount <= 20000) {
                interest = 13;
            } else if (amount > 20000 && amount <= 500000) {
                interest = 15;
            } else if (amount > 500000) {
                interest = -1;
            } else {
                interest = -1;
            }
        }
        return interest;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLbl;
    private javax.swing.JTextField amountTf;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton calcBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel periodLbl;
    private javax.swing.JTextField periodTf;
    private javax.swing.JButton requestBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
