/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ie.ncirl.softeng.loans;

import ie.ncirl.softeng.clients.Client;
import ie.ncirl.softeng.security.SubsystemsGui;
import javax.swing.JOptionPane;

/**
 *
 * @author x12317886
 */
public class LoanSysGui extends javax.swing.JFrame {

    /**
     * Creates new form LoanSysGui
     */
    Client c;
    int l;

    public LoanSysGui(Client c) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JBank Inc.");
        this.c = c;
        l = c.loans.size();
        setLoanList();
    }

    private void setLoanList() {

        String[] loanAmts = {"No loans to display"};
        if (l != 0) {
            loanAmts = new String[l];
            for (int i = 0; i < l; i++) {
                loanAmts[i] = "" + c.loans.get(i).amount;
            }
        }

        loanList.setListData(loanAmts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        titleLbl = new javax.swing.JLabel();
        reqLoanBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        viewStatusBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        loanList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Your Loans");
        titleLbl.setBounds(0, 30, 370, 40);
        jLayeredPane1.add(titleLbl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        reqLoanBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reqLoanBtn.setText("Request a Loan");
        reqLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqLoanBtnActionPerformed(evt);
            }
        });
        reqLoanBtn.setBounds(0, 410, 370, 40);
        jLayeredPane1.add(reqLoanBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backBtn.setBounds(0, 460, 370, 40);
        jLayeredPane1.add(backBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        viewStatusBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewStatusBtn.setText("View Status");
        viewStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatusBtnActionPerformed(evt);
            }
        });
        viewStatusBtn.setBounds(0, 320, 370, 40);
        jLayeredPane1.add(viewStatusBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        loanList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(loanList);

        jScrollPane1.setBounds(10, 130, 350, 170);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Amount borrowed:");
        jLabel1.setBounds(10, 110, 350, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusBtnActionPerformed
        if (l != 0) {
            int currListIndex = loanList.getSelectedIndex();
            String amt = "" + c.loans.get(currListIndex).getAmount();
            String status = c.loans.get(currListIndex).getStatus();
            JOptionPane.showMessageDialog(rootPane, "Amount borrowed: " + amt + "\nStatus: " + status);
        }
    }//GEN-LAST:event_viewStatusBtnActionPerformed

    private void reqLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqLoanBtnActionPerformed
        LoanRequestGui lrg = new LoanRequestGui(c);
        lrg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reqLoanBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        SubsystemsGui sg = new SubsystemsGui(c);
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList loanList;
    private javax.swing.JButton reqLoanBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewStatusBtn;
    // End of variables declaration//GEN-END:variables
}
